name: CI

# trigger
on:
  pull_request:
    types: [closed]
    branches:
      - release

jobs:
  publish:
    # environment
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      # checkout step
      - uses: actions/checkout@v2
      # setup step
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      # build step
      # - name: Build with Maven
      # run: mvn --batch-mode --update-snapshots verify
      # create release step
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.pull_request.title }}
          release_name: ${{ github.event.pull_request.title }}
          body: ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false
      # deploy step
      - name: Publish Packages
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Slack Notification
      # - name: Slack Notification
      #   uses: weseek/ghaction-release-slack-notification@master
      #   with:
      #     channel: "#sip2"
      #     url: ${{ secrets.SLACK_WEBHOOK_URL }}
      #     created_tag: "${{ github.event.pull_request.title }}"
