name: create release pull request

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create-relsease-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      # get version step
      - name: Set Release version env variable
        id: set-version
        run: echo "::set-output name=RELEASE_VERSION::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
      # create release PR step
      - name: Create Release Pull Request
        uses: bakunyo/git-pr-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: release
          GIT_PR_RELEASE_BRANCH_STAGING: main
          GIT_PR_RELEASE_LABELS: release
          RELEASE_VERSION: v${{ steps.set-version.outputs.RELEASE_VERSION }}
          GIT_PR_RELEASE_TEMPLATE: .git-pr-release-template
