name: create release pull request

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create-relsease-pr:
    runs-on: ubuntu-laest
    steps:
      - uses: actions/checkout@v2
      - name: Get Version
      - name: Set Release version env variable
        run: echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Create Release Pull Request
        uses: bakunyo/git-pr-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: release
          GIT_PR_RELEASE_BRANCH_STAGING: main
          GIT_PR_RELEASE_LABELS: release
          RELEASE_VERSION: v${{ env.RELEASE_VERSION }}
          GIT_PR_RELEASE_TEMPLATE: .git-pr-release-template
