name: create release branch

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create-relsease-pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
      # create new branch step
      - name: Create release branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="release/$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
          git checkout -b "$BRANCH_NAME"
          git push origin "$BRANCH_NAME"
