name: create release pull request

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create-relsease-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      # get version step
      - name: Set Release version env variable
        run: echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      # create release PR step
      - name: Create Release Pull Request
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: release
          GIT_PR_RELEASE_BRANCH_STAGING: main
          GIT_PR_RELEASE_LABELS: release
          RELEASE_VERSION: v${{ env.RELEASE_VERSION }}
          GIT_PR_RELEASE_TEMPLATE: .git-pr-release-template
        run: |
          gem install -N git-pr-release
          git-pr-release
